title: Рыжков Дмитрий Сергеевич  
description: Научная и профессиональная деятельность  
permalink: /blog/:year-:month-:day-:title.html  
theme: jekyll-theme-text 
remote_theme: kitian616/jekyll-TeXt-theme 
plugins:
  - jekyll-feed  
  - jekyll-paginate  
  - jekyll-seo-tag 

text_skin: default  # "dark", "forest" и др.  
header_text: true 